services:
  backend:
    build: ./node
    volumes:
      - ./node:/app
      - /app/node_modules  
    ports:
      - "8000:8000"

  frontend:
    build: ./my-app
    volumes:
      - ./my-app:/app
      - /app/node_modules  
    depends_on:
      - backend
    ports:
      - "3000:3000"